Prefer static linking
google/shaderc-rs pull request #143
Opened 2023-11-24 22:24 UTC by acid1103

Fixes #142

2023-11-26 20:00 UTC, antiagainst requested changes
LGTM! just some nits about comments.

2023-11-26 20:00 UTC, antiagainst commented on shaderc-sys/build/build.rs
> +                // if dylib not exist OR prefer static lib and static lib exist, static.
Could you capitalize the first character? Similarly for the following comments (and then them with `.`).

2023-11-27 00:15 UTC, acid1103 commented
Done. :)

2023-11-27 02:48 UTC, antiagainst approved these changes

2023-11-27 02:48 UTC, merged